### PR TITLE
Make doors open instead of vanish

### PR DESCRIPTION
**Pull request by EmeraldLoc**
Note: in testing everything worked, but, previously I had to not allow the player to interact with the object using INTERACT_DOOR and the HOOK_ALLOW_INTERACT hook. I think I fixed it by doing

```
o.hitboxRadius = 0
o.hitboxHeight = 0
```
However, if anyone has reports of entering a door animation, that might be why.

### CODE REVIEW

**Comment by EmilyEmmi** [comment]
I've found two issues with this, being:
- The door opens even if you don't have enough stars
- The door always opens the same direction regardless of which side Mario is on
I was able to fix the first one, but I haven't found a way to deal with the second issue. If you could find a way to fix this, that would be great, otherwise, I will probably still merge this with the fixes to the first issue in place.

**Comment by EmeraldLoc** [comment]
Sorry! I think I know how to fix the second issue, I’ll do it when I get to my computer

**Comment by EmeraldLoc** [comment]
Don't think I can figure out the issue, I can do a bit more later today, but i'm pretty busy today. I did improve the code by removing some unnecessary code (made out of confusion), but can't figure out the problem, sorry! Also you can just merge that fix of yours with the pr, that makes my life a lot easier lol

**Comment by EmilyEmmi** [comment]
Huh, I commit without asking? Weird.

**Pull request merged**
